server:
  rootPath: "/api/*"

databaseHost: "ds053944.mlab.com"
databasePort: 53944
databaseName: "bashdown"
databaseClass: "com.saeedshahab.bashdown.wrappers.mongo.MongoWrapper"

logging:
  level: INFO
  loggers:
    com.saeedshahab.bashdown: DEBUG
  appenders:
  - type: file
    currentLogFilename: /var/log/BashDown.log
    threshold: ALL
    archive: true
    archivedLogFilenamePattern: /var/log/BashDown-%d.log
    archivedFileCount: 10
  - type: console